name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        
      - uses: malinskiy/action-android/install-sdk@release/0.1.2
      
      - run: sdkmanager platform-tools
      
      - uses: malinskiy/action-android/emulator-run-cmd@release/0.1.2
        with:
          api: 30
      
      - run: adb devices
      
      - run: echo $ANDROID_HOME
